name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get -y install make gcc-arm-none-eabi
    - run: make

  pre-commit:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install pre-commit
    - run: pre-commit run --show-diff-on-failure --color=always --all-files
